[workspace]
preview = ["pixi-build"]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64"]
name = "scipystack"

[dependencies]
scipy = { path = "./scipy" }
# ipython = ">=9.3.0,<10"
# pyyaml = ">=6.0.2,<7"
# matplotlib = ">=3.10.3,<4"

[tasks]
start = "python scripts/interp.py"
