name: Linux SciPy

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  test:
    # To enable this job and subsequent jobs on a fork, comment out:
    # if: github.repository == 'rgommers/pixi-dev-scipystack'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pixi-dev-scipystack
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Checkout scipy repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: scipy/scipy
          path: ./scipy/scipy
          submodules: recursive
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.46.0
          manifest-path: scipy/pixi.toml
          #cache: true
          #cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      - name: Build SciPy
        working-directory: ./scipy
        run: pixi run wheel -j2
